#!/bin/bash

[ -f "/opt/mprime/prime.txt" ] || { cat <<-EOF > /opt/mprime/prime.txt
V24OptionsConverted=1
WGUID_version=2
StressTester=0
UsePrimenet=1
DialUp=0
V5UserID=$PRIME_USER
DiskWriteTime=15
NetworkRetryTime=5
NetworkRetryTime2=25
DaysOfWork=2
DaysBetweenCheckins=          1
[PrimeNet]
Debug=0
ProxyHost=
[Worker #1]
WorkPreference=0
EOF
}

[ -f "/opt/mprime/local.txt" ] || { cat <<-EOF > /opt/mprime/local.txt
ComputerID=$HOSTNAME
EOF
}

/opt/mprime/mprime -W/opt/mprime
